name: erptransportexpress
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/loginimage/
    - assets/images/splashscreenimg/

  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/Merriweather-Italic-VariableFont_opsz,wdth,wght.ttf
          style: italic
