final List<Map<String, String>> nashikWarehouses = [
  {"name": "Anusaya Warehousing Complex", "address": "Gut No. 187, Village Jaulke, Taluka Dindori, Nashik"},
  {"name": "Bhaskar Murlidhar Bhamare Sompur VKSS", "address": "Sompur-Baglan, Nashik"},
  {"name": "Bhatgaon VKSS", "address": "Bhatgaon-Chandwad, Nashik"},
  {"name": "Chairman Late Ashokrao Bankar Nagari Sahakari Patsanstha Ltd", "address": "AP Pimpalgaon B, Taluka Niphad, Nashik"},
  {"name": "Dwarkadhish Sakhar Karkhana Ltd.", "address": "Factory Site At Shevarae, Taluka Baglan, Nashik"},
  {"name": "Gangurde Warehouse", "address": "GNo-108, Mz: Jaulke, Taluka Dindori, Nashik"},
  {"name": "Gorakh Narsingrao Balkawade (Bhagur VKS Socy)", "address": "Nasik"},
  {"name": "M/S Agarwal Warehousing", "address": "Vilcholi, Nashik"},
  {"name": "M/S Anand Warehousing", "address": "S No. 156, Mumbai-Agra Highway, At Jaulke (Ozar), Nashik"},
  {"name": "M/S Baphana Warehousing Pvt. Ltd", "address": "Jaulke, Nashik"},
  {"name": "M/S Baphana Warehousing Pvt. Ltd., Tilakwadi", "address": "Tilakwadi, Nashik"},
  {"name": "M/S Dwarakadhish Sakhar Karkhana Ltd.", "address": "Sheware, Nashik"},
  {"name": "M/S Falbag Va Bhajipal K V Sah. Sanstha", "address": "Andursul, Nashik"},
  {"name": "M/S Jondhale’s Warehousing Complex", "address": "Gat No.141/1 & 141/2, Jaulke, Taluka Dindori, Nashik"},
  {"name": "M/S Palkhed VKS", "address": "Niphad, Nashik"},
  {"name": "M/S Pournima Warehousie", "address": "GNo-570, Khambale, Taluka Igatpuri, Nashik"},
  {"name": "M/S S. M Ratnaparkhi", "address": "Girnanagar, Nashik"},
  {"name": "M/S Siddhivinayak Warehousing & Agroprocessing", "address": "GNo-30, Mohadi, Taluka Dindori, Nashik"},
  {"name": "Maharashtra State Warehousing Corporation (MSWC)", "address": "Sinnar, Nashik"},
  {"name": "Maharashtra State Warehousing Corporation (2 units)", "address": "Plot No. E-9, MIDC Sinnar, Nashik"},
  {"name": "Mr Nilesh S Baphana", "address": "Po: Pimpalgaon-Baswant, Tal: Niphad, Nashik"},
  {"name": "Mr Omkar Ramgopal Dhut", "address": "A P Wavi, Tal: Sinnar, Nashik"},
  {"name": "Mr Sunil Kantilal Baphana", "address": "A/P: Pimpalgaon-Baswant, Tal: Niphad, Nashik"},
  {"name": "Central Warehouse, Nashik Road", "address": "Deolali Gaon, Opp Urdu School, Nashik Road, Nashik"},
  {"name": "Ambad (Nashik) Warehouse", "address": "H-105 MIDC, Ambad, Nashik"},
  {"name": "Manmad (APMC Market Yard)", "address": "Chanwad Road, Manmad, Nashik"},
  {"name": "Malegaon (Market Yard)", "address": "Malegaon, Nashik"},
  {"name": "Nampur (APMC Market Yard)", "address": "Nampur, Nashik"},
  {"name": "Kalwan, Market Yard", "address": "Kalwan, Nashik District"},
  {"name": "Lasalgaon, Market Yard", "address": "Lasalgaon, Nashik District"},
  {"name": "Satana, Malegaon Road", "address": "Satana, Nashik District"},
  {"name": "Sinnar Warehouse", "address": "Plot No. E-9, MIDC Sinnar Area, Taluka Sinnar, Nashik"},
  {"name": "Export Facility Mohadi", "address": "Submarket Yard, Mohadi, Taluka Dindori, Nashik"},
  {"name": "Export Facility Kalwan", "address": "APMC, Bhendi Taluka, Kalwan, Nashik"},
  {"name": "Export Facility Chandwad", "address": "APMC, Chandwad, Taluka Chandwad, Nashik"},
  {"name": "Cold Storage Jaulke", "address": "Jaulke Village, Taluka Dindori, Nashik"},
  {"name": "Baphana Warehousing Pvt. Ltd", "address": "Jaulke, Nashik"},
  {"name": "Central Warehouse Nashik Road", "address": "Deolali Gaon, Opp Urdu School, Nashik Road, Nashik"}
];
